### ISSUE TITLE
error when launching the script on Windows 7

### ISSUE THREAD

**Issue by jnowe** [mjbright/futurelearn-dl#6]
Hello,

When I launch the script to get a course (futurelearn-dl.py myaccount@gmail.com mypassword thermodynamics idweek), I get this error:

"SyntaxError: unexpected character after line continuation character"

What I'm doing wrong?

Thanks

**Comment by mjbright** [comment]
You'll have to provide more information.

What version of Python are you using ? - probably you need Python 3.x.

What is the full error message, to see what line produces the syntax error.

**Comment by jnowe** [comment]
File "<stdin>", line 1
   D:\Users\503000809\Downloads\futurelearn-dl.py myaccount@gmail.com mypassword thermodynamics 1
SyntaxError: unexpected character after line continuation character

I'm using Python 3.6.2

**Comment by mjbright** [comment]
OK, thanks.

Maybe it's a line ending problem on Windows.

Don't have acess to a Windows machine right now, but will look at this next
week.

**Comment by xDebuggerx** [comment]
I keep getting this error, any idea why?

C:\>futurelearn-dl.py myaccount@gmail.com mypassword thermodynamics 1
Traceback (most recent call last):
  File "C:\futurelearn-dl.py", line 585, in <module>
    OP_DIR  = os.getenv('OP_DIR',  default=os.getenv('HOME') + '/Education/FUTURELEARN')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
